language: cpp
os: linux
dist: focal
arch:
    - AMD64
    - ppc64le
env:
  global:
    - MAKEFLAGS=-j2
    - PKG_CONFIG_PATH=/tmp/lib/pkgconfig
    - LD_LIBRARY_PATH=/tmp/lib
  jobs:
    - LIBTORRENT_BRANCH=RC_1_1
    - LIBTORRENT_BRANCH=RC_1_2
    - LIBTORRENT_BRANCH=RC_2_0
addons:
  apt:
    packages:
      - libboost-all-dev
      - libfuse-dev
      - libcurl4-openssl-dev
install:
  - env CXXFLAGS="-fpermissive -w" ./scripts/build-libtorrent $LIBTORRENT_BRANCH /tmp
script:
  - autoreconf -i && ./configure && make && make test
